//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuaySo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaiThuong
    {
        public int ID { get; set; }
        public string TenGiai { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string Image { get; set; }
        public Nullable<int> STT { get; set; }
        public int ProcessDefault { get; set; }
        public string TenPhanThuong { get; set; }
        public string GiaTri { get; set; }
    }
}
