//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuaySo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuaySoEntities : DbContext
    {
        public QuaySoEntities()
            : base("name=QuaySoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GiaiThuong> GiaiThuongs { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<TrungGiai> TrungGiais { get; set; }
        public virtual DbSet<NGUOITRUNGGIAI> NGUOITRUNGGIAIs { get; set; }
    }
}
